### ISSUE TITLE
Issues stemming from config_loader.rb not requiring json when using vcloud-launch

### ISSUE THREAD

**Issue by scarby** [gds-operations/vcloud-core#163]
Attempting to use vcloud launch throws an undefined constant error around config_loader.rb
in order to resolve this i needed to ad require 'json' to the file. I will raise a pull request for this

**Comment by mattbostock** [comment]
Thanks for reporting this @scarby. Can you please copy and paste the error you saw?

**Comment by scarby** [comment]
Unfortunately i'm now not been able to replicate this, after removing the require from the gem it continues to function without throwing the error, I'm actually not the only person here to encounter this error when setting up the tool.

However i'm not entirely certain how the json gem is being pulled in now if it wasn't before

though as that gem is used directly in this gem it should probably be required and placed into the gemfile?

**Comment by mattbostock** [comment]
The `json` library is part of Ruby's standard library, e.g.:
http://ruby-doc.org//stdlib-2.0/libdoc/json/rdoc/JSON.html

There is a `json` gem, which `rubocop` uses, but I believe that's a separate JSON implementation to the one used in `config_loader.rb`:

```bash
matt➜govuk/vcloud-gems/vcloud-core(master)» bundle exec gem dependency json --reverse-dependencies
Gem json-1.8.1
  permutation (>= 0, development)
  sdoc (~> 0.3.16, development)
  Used by
    rubocop-0.23.0 (json (< 2, >= 1.7.7))
```

That said, I'm not sure why we don't need to include `require 'json'` since that would be required even to use the standard library `json` implementation. It's difficult to know without an error message.

I'll leave this issue open until someone comes across the same issue. In our testing (and in our CI builds), we are unable to reproduce it.

@scarby If you could please provide more information about which operating system and Ruby version you are using, that would be very helpful.

**Comment by rickard-von-essen** [comment]
I have a case where this shows up with ruby 2.0.0-p481 but is OK with 2.0.0-p247, but it is probably because of the different gemsets. I have not yet found which gem "solves" this. The fix in #164 solves this.

**Comment by rickard-von-essen** [comment]
If I add a printout just before the problem ([/vcloud/core/config_loader.rb - line 30](https://github.com/gds-operations/vcloud-core/blob/master/lib/vcloud/core/config_loader.rb#L30))

```ruby
puts "Loaded gems: #{Gem.loaded_specs.keys}"
```
I can see that ```json``` have been loaded when it works but not when it fails. I guess the conclusion is that this code should ```require 'json'```.

**Comment by mattbostock** [comment]
#170 fixes this issue.

Out of curiosity, I wanted to find why we were unable to reproduce this issue. To do this, I tried to find where `require 'json'` was being invoked using [dtrace](http://dtrace.org/blogs/about/) (which Ruby [supports as of version 2.0.0](https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/)).

The command I used was:

```bash
sudo dtrace -c '/opt/boxen/rbenv/versions/2.2.2/bin/ruby /opt/boxen/rbenv/versions/2.2.2/bin/rspec spec/vcloud/core/config_loader_spec.rb' -Zn 'ruby::require-entry { @[copyinstr(arg0), copyinstr(arg1)] = count(); }'
```

This gave [this output](https://gist.github.com/mattbostock/c5868ac99c3ca9920e66).

I noticed that `json` is [required by the `mime-types` gem](https://gist.github.com/mattbostock/c5868ac99c3ca9920e66#file-dtrace-txt-L639-L640) (version 2.4.3):

```
json                                                /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mime-types-2.4.3/lib/mime/type.rb                1
json                                                /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mime-types-2.4.3/lib/mime/types/loader.rb                1
```

The `mime-types` gem itself is [pulled in by fog-core](https://gist.github.com/mattbostock/c5868ac99c3ca9920e66#file-dtrace-txt-L654):

```
mime/types                                          /opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fog-core-1.28.0/lib/fog/storage.rb                1
```

There's a recent [change](https://github.com/fog/fog-core/commit/7d1835ee986cb48d8bdc22ae87e7d90bdbfe1930#diff-d44181554241f889c23252a99bc08214) in `lib/fog/storage.rb` that is present in versions of `fog-core` v1.31.0 and later; note that currently we [allow versions greater than v1.27.4](https://github.com/gds-operations/vcloud-core/blob/11d6f125670495ac2d12d1472c77b5416d618665/vcloud-core.gemspec#L27) within the version 1 branch.

The change to `lib/fog/storage.rb` means that `mime/types/columnar` is required if available rather than `mime/types`. But `mime/types/columnar`, which was introduced in v2.6.0 of `mime-types`, [does not pull in `json`](https://github.com/mime-types/ruby-mime-types/blob/v2.6.1/lib/mime/types/columnar.rb#L8-L9).

This doesn't explain why @scarby and @rickard-von-essen saw this issue previously (since the issues they raised occured before the change in `lib/fog/storage.rb`, but it's likely to be due to similar reasons.

I was able to reproduce this issue by using `fog-core` v1.31.0 and `mime-types` v2.6.1 (see my [bundle environment](https://gist.github.com/mattbostock/24c81edb449c5a56cf79)).

**Comment by edmundcraske** [comment]
Me too!
'uninitialized constant Vcloud::Core::ConfigLoader::JSON' prevents me from using vcloud-launch. Have manually altered config_loader.rb in my gem home in lieu of an updated gem.

**Comment by mattbostock** [comment]
Thanks for reporting this @edmundcraske. We'll release a new version shortly.

**Comment by alexmuller** [comment]
We've released v1.1.0 to RubyGems: https://rubygems.org/gems/vcloud-core

**Comment by sirstevio** [comment]
I've experienced this same issue installing from ruby-gems last night. It looks to me like the runtime dependencies need to be updated for the other components of the vcloud-tools package on rubygems. Particularly vcloud-launcher. Currently they require version ~>1.0.0 which seems to exclude 1.1.0 and require 1.0.2 still. I've also manually altered the config_loader.rb for the time being and it works OK.

**Comment by mattbostock** [comment]
@sirstevio Would you be happy to raise a pull request against the gds-operations/vcloud-tools repo to fix?

**Comment by sirstevio** [comment]
@mattbostock looking at this a little further I think all that needs to happen is that the latest version of vcloud-launcher is already correct on github and needs pushed to rubygems. I don't believe that's something I can do though or I would happily assist.

**Comment by alexmuller** [comment]
There's a lot in vcloud-launcher that we haven't released so we should definitely do that! https://github.com/gds-operations/vcloud-launcher/pull/103

**Comment by alexmuller** [comment]
We've released [v1.1.0 to RubyGems](https://rubygems.org/gems/vcloud-launcher), thanks for pointing that out.

**Comment by penguindreams** [comment]
This helped me as well. Using the vcloud-edge-configure tool I was getting the "uninitialized constant Vcloud::Core::ConfigLoader::JSON (NameError)" as well. The edge tool was specifically using vcloud-core  version 1.0.2 and not 1.1.0 for some reason. So I just added "require 'json'" to the 1.0.2 version and it's working now.

**Comment by mattbostock** [comment]
Hi @penguindreams, if you upgrade to version 1.5.2 of vCloud Edge Gateway, that version uses vCloud Core 1.1.0, which includes the fix.
